
# Introduction {#intro}

Welcome to this short handbook describing an outbreak dynamics surveillance
system for COVID-19. This infrastructure was developed to provide weekly
assessments of risk levels for different countries in relation to the countries'
overall levels of infection, epidemic growth, and indications of trend
acceleration.


This infrastructure is written in **R**, and relies on the following key
components:

* [*Rmarkdown*](https://rmarkdown.rstudio.com/) (`.Rmd`) reports implementing
  the data gathering, preparation, analysis, and producing synthesis reports
  
* the [*reportfactory*](https://www.reconverse.org/reportfactory/) providing the
  backbone of the infrastructure

* a public [*github*](https://github.com/whocov/trend_analysis_public)
  repository used for hosting files, version control, and automation through
  *github actions*
  


## What does this infrastructure do?

This infrastructure provides an automated data pipeline which gather publicly
available data on COVID-19 cases, deaths, tests, as well as on Variants of
Interest/Concerns (VoI / VoC) and vaccination by country, to provide weekly
assessment of COVID-19 dynamics and levels of risks. The pipeline is implemented
as a [reportfactory](https://www.reconverse.org/reportfactory/) which simplifies
the handling of dependencies, data and scripts, and enables the compilation of
analysis reports locally stored in dedicated, time-stamped folders.


A series of `Rmd` reports performs data gathering, various analysis, and produce
the following information products:

* png figures (*pinplots* and *tadpoles*) summarising the dynamics per WHO
  region, stored on github and visible on the
  [README.md](https://github.com/whocov/trend_analysis_public) page (i.e. landing
  page of the repository)

  
* `rds` files containing the results for each WHO region, also stored on github,
  which can then be used for further investigation or for interactive dashboards
  (e.g. shiny apps); some of these analyses are computer-intensive and would not
  be readily available on dashboards otherwise
  
* automated emails to a specific list of recipients providing a detailed report
  of countries classified into epidemiological risk levels based on incidence,
  growth and trend changes; this latter part is not stored on github
  
  
  
## Content of this handbook

This handbook is organised into the following chapters:

* **Chapter \@ref(getting-started) - [Getting started](#getting-started)**. 
  Instructions to run the infrastructure locally

* **Chapter \@ref(reports) - [Reports overview](#reports)**: outline of the
  `Rmd` reports and how they interact

* **Chapter \@ref(asmodee) - [Implementing ASMODEE](#asmodee)**: methodological
  and pracical considerations for implementing ASMODEE, a new method for trend
  change detection

*  **Chapter \@ref(automation) - [Automation](#automation)**: details on how
   analyses are automated using github actions




## Disclaimer

```{r results = "asis", echo = FALSE}

path_to_md <- here::here("disclaimer.md")
insert_md(path_to_md)

```



## Licensing

This handbook is distributed under the creative-common attribution license
(CC-BY). See [this page](https://creativecommons.org/licenses/by/2.0/) for more
information on the license.

Copyright holder: Thibaut Jombart, 2021
